name: fitness
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  get: ^4.6.6
  iconsax: ^0.0.8
  fluttertoast: ^8.2.8
  email_validator: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.5.0
  direct_select: ^2.0.0
  animated_custom_dropdown: ^3.1.1
  fading_edge_scrollview: ^4.1.1
  shared_preferences: ^2.3.2
  scroll_date_picker: ^3.8.0
  pinput: ^5.0.0
  fancy_intro_carousel_slider: ^0.0.3
  carousel_slider: ^5.0.0 # Check for the latest version on pub.dev
  lottie: ^3.1.2
  animated_segmented_tab_control: ^2.0.0
  dropdown_button2: ^2.3.9
  multiselect_nested: ^1.1.0
  calender_picker: ^2.0.2
  intl: ^0.18.1
  firebase_database: ^11.1.3
  firebase_auth: ^5.3.0
  email_auth: ^2.0.0
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.0.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/myicons/
    - assets/images/
    - assets/illustration/
    - assets/logos/
    - assets/female/
    - assets/male/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600